[default_config]
assembler = "gas"
instruction_set = "arm"

[default_config.opts]
compiler = "/usr/bin/arm-none-eabi-gcc"
compile_flags_txt = ["-mcpu=cortex-m4", "-mthumb", "-ffreestanding", "-fno-builtin", "-g"]
diagnostics = true
